# 1.Print 'Hello HCIA'.

In [2]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [3]:
a=5
b=7
a+b

12

# 3.Define a list and replicate in three different ways.

In [68]:
a=[1,2,3]
b= a.copy()
b1=a
b2=a[:]
print(b)
print(b1)
print(b2)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


# 4.Define two lists and merge them together.

In [6]:
a=[1,2,3]
b=[3,2,1]
print(a+b)

[1, 2, 3, 3, 2, 1]


# 5. Get the last element of the list and print it.

In [7]:
print(a[-1])

3


# 6.Define a tuple that contains only one element.

In [78]:
tpl = '1',
type(tpl)

tuple

# 7.Define a three-line long string.

In [79]:
print( 'Hallo world', 'Roman', 'Nokhrin', sep='\n')

Hallo world
Roman
Nokhrin


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [87]:
tpl = ('1','Hallo world', 'Roman', 'Nokhrin')

for x in tpl:
    print(x)

1
Hallo world
Roman
Nokhrin


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [89]:
a=8
b=6
print(np.dot(a,b))
print(a*b)

48
48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [16]:
import numpy as np
print(np.zeros((5,5),dtype=int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [17]:
import numpy as np
print(np.zeros((4,6),dtype=int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [97]:
import numpy as np
a=np.full((15,1),10)
b=a.reshape(3,5)
print(b)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [100]:
a= np.array([1,2,3,4,5,6])
b= np.array([6,5,4,3,2,1])
print(a)
print(b)
print (np.multiply(a,b))

[1 2 3 4 5 6]
[6 5 4 3 2 1]
[ 6 10 12 12 10  6]
